name: continuos integration
on:
  pull_request:
    branches:
      - 'main'
jobs:
  validate-unit-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ▶️ Run unit tests
        run: |
          npm ci
          npm run test
